#pragma once

/**
 * @file control_iface.hpp
 * @brief Data structures and façade used to coordinate the cross-module data
 * exchange for the obstacle detection and feedback pipeline.
 */

#include <opencv2/opencv.hpp>
#include <vector>

/** @brief Target frames-per-second for the capture loop. */
#define TARGET_FPS 5
/** @brief Sleep duration in milliseconds for worker threads. */
#define THREAD_SLEEP_MS 5
/** @brief Timeout after which feedback is stopped when no commands arrive. */
#define CONTROL_THREAD_SLEEP_MS 7000
/** @brief Debounce period for returning BLE command responses. */
#define COMMAND_RETURN_SLEEP_MS 50
/** @brief Sleep duration when a module is paused. */
#define PAUSED_SLEEP_MS 500

/** @brief Maximum distance (millimeters) considered by the feedback mapper. */
#define MAX_OBSTACLE_DISTANCE 2000

/** @brief Text token for the non-verbal feedback mode. */
#define NON_VERBAL_MODE_STRING "non_verbal"
/** @brief Text token for the verbal feedback mode. */
#define VERBAL_MODE_STRING "verbal"

/**
 * @enum FEEDBACK_MODES
 * @brief Supported audio feedback modalities.
 */
enum FEEDBACK_MODES {
  NON_VERBAL_MODE, /**< Generate spatialized non-verbal audio cues. */
  VERBAL_MODE      /**< Generate synthesized verbal guidance. */
};

/**
 * @struct Frame
 * @brief Container for both the raw depth map and the visualization image
 * produced by the capture module.
 */
typedef struct Frame_ {
  cv::Mat depthMap; /**< Depth values captured from the ToF camera. */
  cv::Mat image;    /**< Colorized representation used for preview/debugging. */
} Frame;

/**
 * @struct Obstacle
 * @brief Geometric and positional description of the most relevant obstacle
 * detected in the current frame.
 */
typedef struct Obstacle_ {
  int label;          /**< Connected-component label identifier. */
  double area;        /**< Area in pixels occupied by the obstacle. */
  double meanDepth;   /**< Average depth (millimeters unless stated otherwise). */
  double score;       /**< Heuristic score indicating detection relevance. */
  double azimuth;     /**< Horizontal angle relative to the user. */
  double elevation;   /**< Vertical angle relative to the user. */
  cv::Point centroid; /**< Centroid in image coordinates. */
  cv::Mat image;      /**< Single-channel mask highlighting the obstacle. */
} Obstacle;

/**
 * @struct Audio
 * @brief Audio buffers and metadata generated by the feedback module.
 */
typedef struct Audio_ {
  std::vector<float> left_signal;  /**< Left channel samples in floating point. */
  std::vector<float> right_signal; /**< Right channel samples in floating point. */
  uint64_t sample_rate;            /**< Sample rate for both channels. */
  float gain;                      /**< Gain factor applied during playback. */
} Audio;

/**
 * @class IControl
 * @ingroup control_module
 * @brief Static façade that exposes synchronization primitives and shared
 * state between the pipeline modules through the @ref ControlModule singleton.
 */
class IControl{
private:
public:
  /**
   * @brief Retrieve the latest frame captured by the image capture module.
   * @return A copy of the captured frame; empty when no frame is available.
   */
  static Frame get_frame();

  /**
   * @brief Store a frame that should be processed by downstream modules.
   * @param frame Frame data produced by the capture module.
   */
  static void set_frame(const Frame& frame);

  /**
   * @brief Retrieve the most recent obstacle detection output.
   * @return Obstacle descriptor; meanDepth is zero when no obstacle is present.
   */
  static Obstacle get_obstacle();

  /**
   * @brief Publish an obstacle descriptor to the shared control state.
   * @param obstacle Details describing the selected obstacle.
   */
  static void set_obstacle(const Obstacle& obstacle);

  /**
   * @brief Retrieve the latest audio buffer produced by the feedback module.
   * @return Audio buffers ready for transmission.
   */
  static Audio get_audio_data();

  /**
   * @brief Publish audio buffers to be consumed by the transmission module.
   * @param data Fully prepared stereo audio buffers.
   */
  static void set_audio_data(const Audio& data);
  
  /**
   * @brief Request the start of the full capture-detect-feedback pipeline.
   */
  static void start_feedback();

  /**
   * @brief Request the shutdown of the full capture-detect-feedback pipeline.
   */
  static void stop_feedback();

  /**
   * @brief Update the feedback playback volume (0-100%).
   * @param volume Volume percentage requested by the configuration module.
   */
  static void set_volume(uint64_t volume);

  /**
   * @brief Select the audio feedback modality to employ.
   * @param mode Desired feedback mode.
   */
  static void set_feedback_mode(FEEDBACK_MODES mode);

  /**
   * @brief Flag that audio-related commands have recently been processed.
   * @param status Whether commands were received.
   */
  static void set_received_audio_commands(bool status);
  
  /**
   * @brief Unlock the internal mutexes guarding shared state. Typically used
   * to bootstrap the pipeline once hardware initialization completes.
   */
  static void unlock_mutexes();

  /** @brief Record the start timestamp for a capture sample. */
  static void add_capture_sample_start();
  /** @brief Record the end timestamp for a capture sample. */
  static void add_capture_sample_end();

  /** @brief Record the start timestamp for a detection sample. */
  static void add_detection_sample_start();
  /** @brief Record the end timestamp for a detection sample. */
  static void add_detection_sample_end();

  /** @brief Record the start timestamp for a feedback sample. */
  static void add_feedback_sample_start();
  /** @brief Record the end timestamp for a feedback sample. */
  static void add_feedback_sample_end();

  /** @brief Record the start timestamp for an audio transmission sample. */
  static void add_transmission_sample_start();
};
